[project]
name = "jirabot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jira>=3.10.5",
    "mypy>=1.19.0",
    "requests>=2.32.5",
    "types-requests>=2.32.4.20250913",
]
